# À propos des auteurs {#auteurs .unnumbered}

[**Samuel Foucher**](https://www.usherbrooke.ca/recherche/fr/specialistes/details/samuel.foucher) est professeur au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Il y enseigne aux [programmes de 1^er^ et 2^e^ cycles de géomatique](https://www.usherbrooke.ca/geomatique/etudes/programmes) les cours *Traitement numérique des images de télédétection*, *Base de données géospatiales* et *Apprentissage profond appliqué à l'observation de la Terre*. Ses intérêts de recherche portent sur le traitement d'images et l'application de l'IA aux données géospatiales.

[**Alexander Jaramillo**](https://www.linkedin.com/in/alexander-jaramillo-zabala-b61b00294) est chargé de cours au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). 

[**Mickaël Germain**](https://www.usherbrooke.ca/geomatique/departement/personnel/personnel-enseignant/mickael-germain) est professeur agrégé au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). Ses expertises comprennent les systèmes d’information géographique (SIG) et leur utilisation sur Internet (SIG web), les systèmes décisionnels, les bases de données à référence spatiale et le forage de données massives. Il s'intéresse également à la cartographie web, à la mobilité, à l’Internet des objets (IoT), à l’apprentissage machine et à la fusion des données multisources pour l’aide à la décision. Ses systèmes sont utilisés dans divers domaines de la géomatique tels que les ressources naturelles, la géologie, les transports et les écosystèmes. De plus, il se passionne pour le traitement, la gestion et l'analyse des données de télédétection pour extraire des paramètres descriptifs facilitant l'identification, la segmentation ou la classification de l'information.

[**Yves Voirin**](https://www.linkedin.com/in/yves-voirin-525b5625) est chargé de cours au [Département de géomatique appliquée](https://www.usherbrooke.ca/geomatique/) de l'[Université de Sherbrooke](https://www.usherbrooke.ca/). 